[package]
name = "lalo-cli"
version = "0.1.0"
authors = ["mauro <maurobalbi@bluewin.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lalo = {version = "0.1.0",path = "../lalo"}